package analyzer;

import picocli.CommandLine;

import java.nio.file.Path;

/**
 * This represents the main entry point to the breaking update analyzer.
 *
 * @author <a href="mailto:gabsko@kth.se">Gabriel Skoglund</a>
 */
public class Main {

    public static void main(String[] args) {
        CommandLineParams params = getCommandLineParams(args);
        BreakingUpdateAnalyzer analyzer = new BreakingUpdateAnalyzer(params.reproductionDir, params.datasetDir);
        analyzer.analyze();
    }

    private static CommandLineParams getCommandLineParams(String[] args) {
        CommandLineParams params = new CommandLineParams();
        CommandLine commandLine = new CommandLine(params);
        try {
            commandLine.parseArgs(args);
        } catch (CommandLine.MissingParameterException e) {
            System.out.println(e.getMessage());
            commandLine.usage(System.out);
            System.exit(1);
        }
        if (commandLine.isUsageHelpRequested() || args.length == 0) {
            System.exit(0);
        }
        return params;
    }

    private static class CommandLineParams {
        @CommandLine.Option(
                names = {"-d", "--dataset-dir"},
                paramLabel = "DATASET-DIR",
                description = "The directory containing the dataset of JSON files, as generated by the GitHubMiner",
                required = true
        )
        Path datasetDir;

        @CommandLine.Option(
                names = {"-r", "--reproduction-dir"},
                paramLabel = "REPRODUCTION-DIR",
                description = "The directory containing the logs and data concerning the reproduction of breaking updates",
                required = true
        )
        Path reproductionDir;
    }
}
